name: Automated rails tests run
run-name: Automated rails tests
on: pull_request
jobs:
  ruby-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      - name: Set up Database
        run: |
          sudo apt-get -yqq install libpq-dev
          cp config/database.yml.github-actions config/database.yml
      - name: Install dependencies
        run: bundle install
      - name: Create database schema
        run: bundle exec rails db:create db:schema:load
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
      - name: Run tests
        run: bundle exec rspec
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
      - name: Send http request for automated tests
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://www.codelix.co.uk/api/notify_automated_tests_successful'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"repo_url": "${{ github.repositoryUrl }}", "pr_number": "${{ github.event.number }}", "opened_by_github_username": "${{ github.actor }}"}'
