name: Exercise attempt PR approved
run-name: PR approved
on:
  pull_request_review:
    types: [submitted]
jobs:
  send-http-request:
    runs-on: ubuntu-latest
    steps:
      - name: Sending request step name
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://www.codelix.co.uk/api/notify_pr_approved'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"approver": "${{ github.actor }}", "ref_name": "${{ github.ref_name }}", "repo_url": "${{ github.repositoryUrl }}"}'
        if: github.event.review.state == 'approved'
